//
// Created by alex on 10/12/15.
//

#ifndef METADIFF_CORE_H
#define METADIFF_CORE_H


namespace metadiff {
    /**
     * The maximum number of symbolic integers allowed (lower might be even more sensible)
     */
    const size_t N = 100;

    /**
     * A constant for certain operations along axis, specifying to auto infer the correct axes
     */
    const size_t AUTO_INFER_AXIS = 1000;

    /**
     * A symbolic integer is just a SymbolicPolynomial
     */
    typedef symbolic::SymbolicPolynomial<N, unsigned short> SymInt;

    /**
     * Currently we support 4 dimensional arrays, so the Shape is an array of 4 symbolic integers
     */
    typedef std::array<SymInt,4> Shape;

    enum ad_node_type{
        /**
         * The node is just a SymInt, which interacts with other nodes in an operator
         */
                SYMBOLIC_INTEGER,
        /**
         * The node is a constant
         */
                CONSTANT,
        /**
         * The node is derived from a constant, trough some operator manipulations
         */
                CONSTANT_DERIVED,
        /**
         * The node is an input
         */
                INPUT,
        /**
         * The node is a shared variable
         */
                SHARED_INPUT,
        /**
         * The node is derived from at least one input
         */
                INPUT_DERIVED
    };

    enum ad_value_type{
        /**
         * Represents floating point values, inrespectable of precision
         */
                FLOAT,
        /**
         * Represents integer values, inrespectable of precision
         */
                INTEGER,
        /**
         * Represents boolean values
         */
                BOOLEAN
    };

    enum ad_device_type {
        /**
         * The device is one or more CPUs
         */
                CPU,
        /**
         * The device is a single GPU
         */
                GPU
    };

    enum ad_implicit_broadcast {
        /**
         * If any node performs an implicit broadcast an exception is thrown
         */
                RAISE,
        /**
         * If any node performs an implicit broadcast a warning is printed to the standard output
         */
                WARN,
        /**
         * If any node performs an implicit broadcast there is no notification
         */
                QUIET
    };

    enum ad_float_type {
        /**
         * 16 bit floating point number
         */
                f16,
        /**
         * 32 bit floating point number
         */
                f32,
        /**
         * 64 bit floating point number
         */
                f64,
    };
    enum ad_integer_type {
        /**
         * Signed 8 bit integer
         */
                s8,
        /**
         * Unsigned 8 bit integer
         */
                u8,
        /**
        * Signed 16 bit integer
        */
                s16,
        /**
         * Unsigned 16 bit integer
         */
                u16,
        /**
        * Signed 32 bit integer
        */
                s32,
        /**
         * Unsigned 32 bit integer
         */
                u32,
        /**
        * Signed 64 bit integer
        */
                s64,
        /**
         * Unsigned 64 bit integer
         */
                u64
    };

    /**
     * A single computational device to facilitate multy node computations
     * TODO not yet well designed, high probability it will change in the future
     */
    class Device{
    public:
        /**
         * Type of the device
         */
        ad_device_type type;
        /**
         * Id of the device
         */
        size_t id;
        Device():
                type(ad_device_type::CPU),
                id(0) {};

        Device(const ad_device_type type, const size_t id):
                type(type),
                id(id) {};

        Device(Device& device):
                type(device.type),
                id(device.id) {};
    };

    /**
     * The class provides data generated by the graph optimizer relevant to the backends
     * TODO Also this is not yet complete, high probability it will expand in the future
     */
    class ExecutionData{
    public:
        /**
         * Whether the node should be inlined
         */
        bool inlined;
        /**
         * Whether the node should be operated in place
         * This is possible only when some of the operands lifespan expires
         */
        bool inplace;
        /**
         * The graph optimizer register allocation
         */
        size_t register_id;
        /**
         * For synchronization and memory allocation this will contain the time step after
         * which the node can be destroyed
         */
        size_t lifespan;
        ExecutionData():
                inlined(false),
                inplace(false),
                register_id(0),
                lifespan(0) {};

        ExecutionData(const ExecutionData& data):
                inlined(data.inlined),
                register_id(data.register_id),
                lifespan(data.lifespan) {};
    };

    /**
     * The class represents a group of nodes and other groups together.
     * The hierarchy is a DAG as well starting with a single root group.
     * The main goal of the groups is to provide a better way of visualizing the computation network
     */
    class NodeGroup{
    public:
        /**
         * The standard delimiter for hierarchical group names
         */
        static const char delimiter = '/';
        /**
         * Name of the group
         */
        const std::string name;
        /**
         * The group parent
         */
        const std::weak_ptr<NodeGroup> parent;
        /**
         * Vector of group children
         */
        std::vector<std::weak_ptr<NodeGroup>> children;
        NodeGroup():
                name("_root"){};

        NodeGroup(std::string name, std::weak_ptr<NodeGroup> parent):
                name(name),
                parent(parent) {};

        /**
         * Returns the full name of the group, traversing all its ancestors
         */
        std::string get_full_name() const{
            std::string full_name = name;
            NodeGroup* node = parent.lock().get();
            while(node->name != "_root"){
                full_name = node->name + delimiter + full_name;
                node = node->parent.lock().get();
            }
            return full_name;
        }
    };

    class GraphInternal;
    typedef GraphInternal* GraphInPtr;
    typedef std::shared_ptr<GraphInternal> Graph;
    typedef std::weak_ptr<NodeGroup> Group;
    class NodeInternal;

    /**
     * The class is an API wrapper around node of the graph
     */
    class Node {
    public:
        std::weak_ptr<NodeInternal> ptr;

        Node(){};

        /**
         * Unwraps the pointer to the internal node. Exits the program if the pointer has expired
         */
        std::shared_ptr<NodeInternal> unwrap() const;

        Node(const std::shared_ptr<NodeInternal> ptr):
                ptr(ptr) {};

        Node(const Node& node):
                ptr(node.ptr) {};

        Node(const Node* node):
                ptr(node->ptr) {};

//        /**
//         * Checks if the Node is empty, could happen only if you manually construct this class
//         * or the Graph instance is out of scope.
//         */
//        bool empty() const{
//            return ptr.expired();
//        }

        /**
         * Copies the node to another graph, by using the ancestors provided
         */
        void copy_to(GraphInPtr graph, std::vector<Node> ancestors) const;

        bool is_constant() const;
        bool is_scalar() const;
        bool is_vector() const;
        bool is_vector_strict() const;
        bool is_matrix() const;
        bool is_matrix_strict() const;
        bool is_tensor3() const;
        bool is_tensor3_strict() const;
        bool is_tensor4_strict() const;

        void update(Node update);
        Node alias();
        Node broadcast(Shape shape);
        Node broadcast_to(Node other);

        Node neg();
        Node div();
        Node sum(std::vector<size_t> axes = {0, 1, 2, 3});
        Node square();

        Node constant();
        Node nt();
        Node gt(Node node);
        Node ge(Node node);
        Node lt(Node node);
        Node le(Node node);
        Node eq(Node node);
        Node neq(Node node);
        Node approx_eq(Node node, double tol=0.00001);
        Node approx_neq(Node node, double tol=0.00001);
        Node logical_and(Node node);
        Node logical_or(Node node);
        Node zero_elem();
        Node non_zero_elem();
        Node is_nan();
        Node is_inf();
        Node select(Node result_true, Node result_false);

        Node exp();
        Node log();
        Node log1p();
        Node softplus(size_t threshold = 50);
        Node abs();
        Node sigmoid();
        Node relu();
        Node sin();
        Node cos();
        Node tan();
        Node cot();
        Node sinh();
        Node cosh();
        Node tanh();
        Node coth();
        Node pow(Node power);
        Node pow(double power);

        Node transpose();
        Node minv();
        Node det();
        Node logdet();
        Node trace();

        Node diag();
        Node reshape(Shape shape);
        Node flatten(size_t ndim = 1);
        Node reorder(std::array<size_t, 4> order);
        Node reorder(size_t dim0, size_t dim1, size_t dim2=2, size_t dim3=3);

        Node slice(Node index, size_t axis = 0);
        Node index(Node index, size_t axis = AUTO_INFER_AXIS);

        Node max(size_t axis = AUTO_INFER_AXIS);
        Node argmax(size_t axis = AUTO_INFER_AXIS);
        Node sort(size_t axis = AUTO_INFER_AXIS);
        Node argsort(size_t axis = AUTO_INFER_AXIS);
    };
    typedef std::vector<Node> NodeVec;
    typedef std::vector<std::pair<Node, Node>> Updates;

    /**
     * Abstract class for operators
     */
    class Operator{
    public:
        /**
         * Pointer to the owning graph
         */
        GraphInPtr graph;
        /**
         * Pointer to the owning node
         */
        Node owner;
        /**
         * Unique name of the concrete operator classes
         */
        const std::string name;
        Operator(std::string name,
                 GraphInPtr graph):
                name(name),
                graph(graph){};

        /**
         * Copies the operator to a new graph
         */
        virtual std::shared_ptr<Operator> copy_to(GraphInPtr graph, std::vector<Node> ancestors) const = 0;
        /**
         * Gives the value type of the result node of the operator
         */
        virtual ad_value_type get_value_type() const = 0;

        /**
         * Gives the shape of the result node of the operator
         */
        virtual Shape get_shape() const = 0;
        /**
         * Gives the node type of the result node of the operator
         */
        virtual ad_node_type get_node_type() const = 0;
        /**
         * Gives the gradient level of the node result of the operator
         */
        virtual size_t get_gradient_level() const = 0;
        /**
         * Gives the parents of the node result of the operator
         */
        virtual NodeVec get_parents() const = 0;
        /**
         * Gives the arguments of the node result of the operator
         */
        virtual NodeVec get_arguments() const = 0;
        /**
         * A function which should compute and return the gradient with respect
         * to the parent and the specified index, given the gradient of the owner node
         */
        virtual Node get_parent_grad(Node my_grad, size_t index) = 0;
        /**
         * Sends a gradient message to the target by either inserting it in the messages
         * if none exists, or accumulating them
         */
        void send_grad_message(size_t target, Node msg, std::vector<Node>& messages) const;
        /**
         * Generates all gradients, given the current setup of the graph
         */
        virtual void generate_gradients(std::vector<Node>& messages);
//        /**
//         * Returns a scalar value if the operator is constant
//         */
//        double get_scalar_value() const;
        /**
         * Compares only if this operator is equal to the other, not the other way around.
         * Note that although equality is symmetric, because of mathematical idenitities
         * and the fact that the code is with each operator separately the true equality
         * operator is `op1.equals(op2) or op2.equals(op1)`
         * TODO this and the symbolic_equals are things which aren't yet well done
         */
        virtual bool equals(const std::shared_ptr<Operator> op) const = 0;
        /**
         * Returns the union of the parents and arguments of the node result of the operator
         */
        NodeVec get_ancestors() const;
    };

    /**
     * Internal class for a graph node, contains all of the metadata
     */
    class NodeInternal{
    public:
        GraphInPtr graph;
        Device device;
        size_t id;
        std::string name;
        ad_node_type type;
        ad_value_type v_type;
        Shape shape;
        std::shared_ptr<Operator> op;
        NodeVec children;
        size_t grad_level;
        // Value variables (how can we make this better?)
        SymInt sym_value;
        af::array value;
        SharedPtr shared;
        // Data populated by the optimizer
        ExecutionData execution;
        Group group;

        NodeInternal(GraphInPtr graph, Device device):
                graph(graph),
                device(device) {}

        NodeInternal(GraphInPtr graph,
                     Device device,
                     size_t id,
                     std::string name,
                     ad_node_type type,
                     ad_value_type v_type,
                     Shape shape,
                     std::shared_ptr<Operator> op,
                     size_t grad_level,
                     Group group):
                graph(graph),
                device(device),
                id(id),
                name(name),
                type(type),
                v_type(v_type),
                op(op),
                grad_level(grad_level),
                shape(shape),
                group(group){}
    };

    /**
     * Internal class for a compute graph
     */
    class GraphInternal : public std::enable_shared_from_this<GraphInternal> {
    private:
        std::vector<Node> temporary_constants;
        std::vector<size_t> temporary_updates;
    public:
        std::string name;
        Device default_device;
        ad_float_type f_type;
        ad_integer_type i_type;
        ad_implicit_broadcast broadcast;

        size_t sym_integer_count;
        std::vector<std::shared_ptr<NodeInternal>> nodes;
        std::vector<SharedPtr> shared_vars;
        Updates updates;

        std::vector<std::shared_ptr<NodeGroup>> groups;
        size_t gradient_mode;
        Group current_group;

        GraphInternal() {
            // TODO Have a better preference of devices available in order
            name = "Function";
            sym_integer_count = 0;
            default_device = Device(CPU, 0);
            f_type = ad_float_type::f32;
            i_type = ad_integer_type::s32;
            broadcast = ad_implicit_broadcast::RAISE;
            groups.push_back(std::make_shared<NodeGroup>());
            gradient_mode = 0;
            current_group = groups[0];
        }

        bool is_temporary_constant(Node node) const;
        /**
         * Copies the computation of the nodes in the mask to another graph
         */
        NodeVec copy(GraphInPtr new_graph, std::vector<bool> mask) const;
        /**
         * Returns an array masking all descendants of the marked nodes
         * TODO Currently assumes that the nodes are ordered in order of computation
         */
        std::vector<bool> get_descendants_mask(NodeVec marked) const;
        /**
         * Returns an array masking all ancestors of the marked nodes
         * TODO Currently assumes that the nodes are ordered in order of computation
         */
        std::vector<bool> get_ancestors_mask(NodeVec marked) const;
        /**
         * Finds a node which performs the same operation
         */
        Node find_same_node(std::shared_ptr<Operator> op);
        /**
         * Adds temporary updates to the graph
         */
        void add_temporary_updates(const Updates& updates);
        /**
         * Removes all temporary updates of the graph
         */
        void clear_temporary_updates();
        /**
         * Returns the gradients of the objective with respect to the parameters provided
         */
        std::vector<Node> gradient(Node objective, std::vector<Node> params);
        /**
         * Optimizes a graph with respect to the given nodes (INTERNAL)
         */
        Graph optimize(NodeVec& targets, Updates& updates,NodeVec& inputs,
                       NodeVec& new_targets, Updates& new_updates, NodeVec& new_inputs);

        /**
         * Creates a new shared variable
         * TODO This should be made independ from arrayfire as well as the whole SharedVariable class
         */
        Node shared_var(af::array value, std::string name = "SharedVar");
        /**
         * Creates a new derived node (INTERNAL)
         */
        Node derived_node(std::shared_ptr<Operator> op);
        /**
         * Adds an update for the shared node
         */
        void update_node(Node shared, Node update);
        /**
         * Creates a new constant node
         * TODO This should be made independ from arrayfire as well as the whole SharedVariable class
         */
        Node constant_node(af::array value);

        /**
         * Returns the next unused symbolic integer
         */
        SymInt get_new_symbolic_integer();

        /**
         * Returns the group specified with by the name or creates it
         */
        Group get_group(std::string full_name);

        /**
         * Sets the current group to the specified by the name
         * If it does not exists creates it
         */
        void set_group(std::string full_name);

        /**
         * Sets the current group to the group specified by the name (not full)
         * and it being a child of the provied parent
         */
        void set_group(std::string name, Group parent);

        /**
         * Sets the current group to the _root
         */
        void reset_group();

        Node tensor(ad_value_type v_type,
                    std::array<SymInt, 4> shape,
                    std::string name = "InputTensor");
        Node tensor(ad_value_type v_type,
                    SymInt shape0,
                    SymInt shape1,
                    SymInt shape2,
                    SymInt shape3,
                    std::string name = "InputTensor");
        Node tensor(ad_value_type v_type,
                    std::string name = "InputTensor");
        Node tensor_as(Node node,
                       std::string name = "InputTensor");
        Node tensor3(ad_value_type v_type,
                     std::array<SymInt, 3> shape,
                     std::string name = "InputTensor3");
        Node tensor3(ad_value_type v_type,
                     SymInt shape0,
                     SymInt shape1,
                     SymInt shape2,
                     std::string name = "InputTensor3");
        Node tensor3(ad_value_type v_type,
                     std::string name = "InputTensor3");
        Node tensor3_as(Node node,
                        std::string name = "InputTensor3");
        Node matrix(ad_value_type v_type,
                    std::array<SymInt, 2> shape,
                    std::string name = "InputMatrix");
        Node matrix(ad_value_type v_type,
                    SymInt shape0,
                    SymInt shape1,
                    std::string name = "InputMatrix");
        Node matrix(ad_value_type v_type,
                    std::string name = "InputMatrix");
        Node matrix_as(Node node,
                       std::string name = "InputMatrix");
        Node square_matrix(ad_value_type v_type,
                           SymInt shape,
                           std::string name = "InputMatrix");
        Node vector(ad_value_type v_type,
                    SymInt shape,
                    std::string name = "InputVector");
        Node vector(ad_value_type v_type,
                    std::string name = "InputVector");
        Node vector_as(Node node,
                       std::string name = "InputVector");
        Node scalar(ad_value_type v_type,
                    std::string name = "InputScalar");

        Node eye(SymInt size);
        Node ones(Shape shape);
        Node zeros(Shape shape);
        Node constant_value(double value, Shape shape = {1, 1, 1, 1});
        Node seq(SymInt start, SymInt end);
    };

    /**
     * Skips any alias operators to get the base operator
     */
    std::shared_ptr<Operator> get_base_op(const std::shared_ptr<Operator> op);

    /**
     * Check if two nodes are symbolically equivalent.
     */
    bool symbolic_equals(const Node& node1, const Node& node2);


    /**
     * Convinience for applying an operator trough template
     */
    template <typename T>
    Node apply(Node node) {
        return node.unwrap()->graph->derived_node(std::make_shared<T>(node.unwrap()->graph, node));
    }

    /**
     * Convinience for applying an operator trough template
     */
    template <typename T>
    Node apply(Node parent1, Node parent2){
        GraphInPtr graph = parent1.unwrap()->graph;
        return graph->derived_node(std::make_shared<T>(graph, parent1, parent2));
    }

    /**
     * Convinience for applying an operator trough template
     */
    template <typename T>
    Node apply(NodeVec parents){
        GraphInPtr graph = parents[0].unwrap()->graph;
        return graph->derived_node(std::make_shared<T>(graph, parents));
    }

    std::string to_string(ad_node_type const & type){
        switch(type){
            case ad_node_type::SYMBOLIC_INTEGER: return "SYMBOLIC_INTEGER";
            case ad_node_type::CONSTANT: return "CONSTANT";
            case ad_node_type::INPUT : return "INPUT";
            case ad_node_type::SHARED_INPUT : return "SHARED";
            case ad_node_type::INPUT_DERIVED: return "DERIVED";
            case ad_node_type::CONSTANT_DERIVED: return "CONSTANT_DERIVED";
        }
        return "UNREACHABLE";
    }

    std::string to_string(ad_value_type const & type){
        switch(type){
            case ad_value_type::FLOAT: return "FLOAT";
            case ad_value_type::INTEGER: return "INTEGER";
            case ad_value_type::BOOLEAN: return "BOOLEAN";
        }
        return "UNREACHABLE";
    }

    std::string to_string(ad_device_type const & type){
        switch(type){
            case ad_device_type::CPU: return "CPU";
            case ad_device_type::GPU: return "GPU";
        }
        return "UNREACHABLE";
    }

    std::string to_string(ad_implicit_broadcast const & type){
        switch(type){
            case ad_implicit_broadcast::RAISE: return "Raise";
            case ad_implicit_broadcast::WARN: return "Warn";
            case ad_implicit_broadcast::QUIET: return "Quiet";
        }
        return "UNREACHABLE";
    }

    std::string to_string(ad_float_type const & type){
        switch(type){
            case ad_float_type::f16: return "f16";
            case ad_float_type::f32: return "f32";
            case ad_float_type::f64: return "f64";
        }
        return "UNREACHABLE";
    }

    std::string to_string(ad_integer_type const & type){
        switch(type){
            case ad_integer_type::s8: return "s8";
            case ad_integer_type::u8: return "u8";
            case ad_integer_type::s16: return "s16";
            case ad_integer_type::u16: return "u16";
            case ad_integer_type::s32: return "s32";
            case ad_integer_type::u32: return "u32";
            case ad_integer_type::s64: return "s64";
            case ad_integer_type::u64: return "u64";
        }
        return "UNREACHABLE";
    }

    std::string to_string(Device const & device){
        return to_string(device.type) + "[" + std::to_string(device.id) + "]";
    }

    std::ostream & operator<<(std::ostream & f, ad_node_type const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, ad_value_type const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, ad_device_type const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, ad_implicit_broadcast const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, ad_float_type const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, ad_integer_type const & type) {
        f << to_string(type);
        return f;
    }

    std::ostream & operator<<(std::ostream & f, Device const & device) {
        f << to_string(device);
        return f;
    }
}

#endif //METADIFF_CORE_H